### DISCUSSION TITLE
Redis Cluster and configuration setting with signal-server

### DISCUSSION THREAD

**Discussion by akcachy** [indrawp/Setup-Guide#100] [Q&A]
Hi Everyone,

Facing Issue while deploying my Signal-Server-V-5.31

Use case :- 
I took 2 client which is Signal Android configured to our self deployed signal server.

- When Both client are opened 
   - Sending message to eachother are sent and checked on server messages are recieving at their end but my message to eachother never exchanged to eachother.
   - But once a client user app is killed and repoened all the messages came which was earlier sent by other client
   
Checked all things and debugged but not able to resolve the issue.

**My observation:**

There are things which i suspect is wrong 

1. Configuration of redis with sample.yml

```
cacheCluster: # redis server for cache cluster
  urls:
    - redis://127.0.0.1:7001/1 # change to your redis server
clientPresenceCluster: # redis server for cache cluster
  urls:
    - redis://127.0.0.1:7001/ 2# change to your redis server
metricsCluster: # redis server for cache cluster
  urls:
    - redis://127.0.0.1:7001/3 # change to your redis server
pushSchedulerCluster: # redis server for push scheduler
  urls:
    - redis://127.0.0.1:7001/ 4# change to your redis server
pubsub: # redis server for pubsub cache
  url: redis://127.0.0.1:7001/pubsub # change to your redis server
  replicaUrls:
    -  redis://127.0.0.1:7001/pubsubReplica # change to your redis server
messageCache: # Redis server configuration for message store cache
  cluster:
    urls:
      - redis://127.0.0.1:7001/ 1
```
2. pubsub is not working properly to deliver messages.

Any help would be appreciated.

Please let me know in case i am not clear with my issue
